version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "2552:6379"
    volumes:
      - $PWD/redis-data:/root/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=1